{
 "title": ".NET runtime metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "pod", "label": "pod", "query": "dotnet_build_info" }
  ]
 },
 "panels": [
  {
   "title": "Current Application Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "% CPU consumption",
     "type": "singlestat",
     "description": "The percentage of available CPU resources consumed.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{pod=\"$pod\"}[$__interval]) / process_cpu_count{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "% Memory consumption",
     "type": "singlestat",
     "description": "The percentage of available memory resources consumed.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_working_set_bytes{pod=\"$pod\"} / dotnet_gc_memory_total_available_bytes{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "% Paused time",
     "type": "singlestat",
     "description": "The percentage of time that the application was paused to allow the garbage collector to run.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "dotnet_gc_pause_ratio{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "% GC CPU consumption",
     "type": "singlestat",
     "description": "The percentage of total process CPU utilization that was dedicated to performing garbage collections.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "dotnet_gc_cpu_ratio{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Thread pool queue length",
     "type": "singlestat",
     "description": "The average length of the thread pool's work queue. Values greater than 0 indicate a problem.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(dotnet_threadpool_queue_length_sum{pod=\"$pod\"}[$__rate_interval]))  / \nsum(rate(dotnet_threadpool_queue_length_count{pod=\"$pod\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "% JIT CPU consumption",
     "type": "singlestat",
     "description": "The percentage of CPU utilization that was dedicated to compiling methods by the Just In Time (JIT) compiler.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "dotnet_jit_cpu_ratio{pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Exceptions/ sec",
     "type": "singlestat",
     "description": "The rate of exceptions being thrown per second",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(dotnet_exceptions_total{pod=\"$pod\"}[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  { "title": "Memory / Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Memory use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes{pod=\"$pod\"}",
     "legendFormat": "# bytes (in physical memory)"
    },
    {
     "expr": "dotnet_gc_memory_total_available_bytes{pod=\"$pod\"}",
     "legendFormat": "Total bytes available (memory limit)"
    }
   ]
  },
  {
   "title": "Heap size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dotnet_gc_heap_size_bytes{pod=\"$pod\"}",
     "legendFormat": "gen {{gc_generation}}"
    }
   ]
  },
  {
   "title": "GC CPU + pause ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dotnet_gc_cpu_ratio{pod=\"$pod\"}",
     "legendFormat": "GC CPU %"
    },
    {
     "expr": "dotnet_gc_pause_ratio{pod=\"$pod\"}",
     "legendFormat": "GC Pause %"
    }
   ]
  },
  {
   "title": "Number of GC collections/ sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_collection_count_total{pod=\"$pod\"}[$__interval])) by (gc_generation, gc_reason)",
     "legendFormat": "gen {{gc_generation}}: {{gc_reason}}"
    }
   ]
  },
  {
   "title": "Bytes allocated (by heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_allocated_bytes_total{pod=\"$pod\"}[$__interval])) by (gc_heap)",
     "legendFormat": "Alloc bytes {{gc_heap}}"
    }
   ]
  },
  {
   "title": "Average GC duration (by generation)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_seconds_sum{pod=\"$pod\"}[$__interval])) by (gc_generation) / sum(increase(dotnet_gc_collection_seconds_count{pod=\"$pod\"}[$__interval])) by (gc_generation) ",
     "legendFormat": "{{gc_generation}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(dotnet_gc_collection_seconds_bucket{pod=\"$pod\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Thread pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Thread pool queue length",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (le) (increase(dotnet_threadpool_queue_length_bucket{pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Num thread pool threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_threadpool_num_threads{pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Num thread timers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_threadpool_timer_count{pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Thread pool adjustment reasons",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dotnet_threadpool_adjustments_total{pod=\"$pod\"}[$__interval])) by (adjustment_reason )",
     "legendFormat": "{{adjustment_reason}}"
    }
   ]
  },
  { "title": "JIT compliation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Methods compiled/ sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dotnet_jit_method_total{dynamic=\"true\", pod=\"$pod\"}[$__interval])",
     "legendFormat": "Dynamic methods"
    },
    {
     "expr": "rate(dotnet_jit_method_total{dynamic=\"false\", pod=\"$pod\"}[$__interval])",
     "legendFormat": "Methods"
    }
   ]
  },
  {
   "title": "JIT CPU usage ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dotnet_jit_cpu_ratio{pod=\"$pod\"}",
     "legendFormat": "% CPU utilization"
    }
   ]
  },
  { "title": "Contention", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Locks contended/ sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dotnet_contention_total{pod=\"$pod\"}[$__interval])",
     "legendFormat": "# Locks contended"
    }
   ]
  },
  {
   "title": "Time waiting for locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(dotnet_contention_seconds_total{pod=\"$pod\"}[$__interval])",
     "legendFormat": "Waiting time"
    }
   ]
  },
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Exceptions/ sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dotnet_exceptions_total{pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Sockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Bytes sent vs received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(dotnet_sockets_bytes_received_total[$__rate_interval])",
     "legendFormat": "Received/ sec"
    },
    {
     "expr": "rate(dotnet_sockets_bytes_sent_total[$__rate_interval])",
     "legendFormat": "Sent/ sec"
    }
   ]
  },
  {
   "title": "Connections established",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dotnet_sockets_connections_established_incoming_total[$__rate_interval])",
     "legendFormat": "Incoming "
    },
    {
     "expr": "increase(dotnet_sockets_connections_established_outgoing_total[$__rate_interval])",
     "legendFormat": "Outgoing"
    }
   ]
  }
 ]
}